services:
    sigepa:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sigepa
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor
        networks:
            - laravel-network
        environment:
            - DB_CONNECTION=mysql
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=homestead
            - DB_USERNAME=root
            - DB_PASSWORD=root

    db:
        image: mysql:5.7
        container_name: laravel-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: homestead
        networks:
            - laravel-network

networks:
    laravel-network:
        driver: bridge
